steps:
  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - './frontend'

  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-backend:latest'
      - './backend'

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-frontend:latest']

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-backend:latest']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE_NAME}' # Substitution variable for backend service name
      - '--image'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-backend:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'vinci-dev@${PROJECT_ID}.iam.gserviceaccount.com' # Assumes this service account exists

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE_NAME}' # Substitution variable for frontend service name
      - '--image'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-frontend:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'vinci-dev@${PROJECT_ID}.iam.gserviceaccount.com' # Assumes this service account exists

images:
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-frontend:latest'
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/vinci-clips/vinci-clips-backend:latest'

# Default substitution values (can be overridden in the trigger)
substitutions:
  _FRONTEND_SERVICE_NAME: 'vinci-clips-frontend' # Replace with your actual frontend service name
  _BACKEND_SERVICE_NAME: 'vinci-clips-backend'   # Replace with your actual backend service name
  _NEXT_PUBLIC_API_URL: '' # The public URL of your backend service, e.g., https://vinci-clips-backend-xyz.a.run.app

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'